AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    Runtime: python3.9
    Environment:
      Variables:
        TABLE_NAME: !Ref LinksTable

Resources:
  LinksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: drive_links
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: slug
          AttributeType: S
      KeySchema:
        - AttributeName: slug
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expires_at
        Enabled: true

  LinkPulseApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
        AllowOrigin: "'*'"

  ShortenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers.shorten_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LinksTable
      Events:
        ShortenApi:
          Type: Api
          Properties:
            RestApiId: !Ref LinkPulseApi
            Path: /shorten
            Method: post

  RedirectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers.redirect_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LinksTable
      Events:
        RedirectApi:
          Type: Api
          Properties:
            RestApiId: !Ref LinkPulseApi
            Path: /u/{slug}
            Method: get

  AnalyticsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers.analytics_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref LinksTable
      Events:
        AnalyticsApi:
          Type: Api
          Properties:
            RestApiId: !Ref LinkPulseApi
            Path: /analytics/{slug}
            Method: get

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${LinkPulseApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"